name: server
description: Firebase functions.

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  client_server:
    path: ../client_server
  firebase_functions_interop:
    git:
      url: git://github.com/ntaoo/firebase-functions-interop
      branch: update_deps
  firebase_admin_interop: ^2.1.0

dev_dependencies:
  args: ^1.6.0
  grinder: 0.8.5
  pedantic: ^1.9.0
  test: ^1.14.3
  mockito: ^4.1.1
  # Needed to compile Dart to valid Node.js module.
  build_runner: ^1.7.4
  build_node_compilers: ^0.2.4